### PR TITLE
Dockerize webapp

### PR DESCRIPTION
**Pull request by brandomr**
# What's new
This PR implements a Docker container for this project.

## Setup
The default index for the Docker container is located in `docker/index`. If you want to build the container with a different index, you should replace this. You also need to ensure that `src/main/resources/application.conf` has `odinson.indexDir = "/root/webapp/docker/index"` for its index.

## Usage
You can build the container with:

```
docker build -t odinsonwebapp .
```

This generates a container named `odinsonwebapp`, which can be run using:

```
docker run -it --rm -v $PWD:/root/webapp -p 9000:9000 -m=4gb -d odinsonwebapp
```

Then you can send requests to the container as you would the app running in the foreground. You can also navigate to `http://localhost:9000` where you are running the container to use the webapp.

## Issues
The Play framework runs in the background in the container unless you run the container in interactive mode (with the `-it` flag). This may be problematic when using docker-compose.

Also, the default index at `docker/index` has a couple hundred documents. This is several MB, so a smaller default index would decrease the size of the repo.

### CODE REVIEW

**Comment by BeckySharp** [comment]
thanks for the PR!!! 🎉 
let me review it, prob Monday :)

**Comment by BeckySharp** [comment]
Hi again! First of all, "I love what you did with the place" :)
Thanks for working on this, having a docker container would be great!
The PR looks great overall, my only concern is with committing the index (since the files are binaries and won't track well, etc).
Is it possible for you to modify the docker container such that it mounts a local directory instead? And people can make sure they put their index there?
Thanks!

**Comment by brandomr** [comment]
I can definitely do that--the reason I added it was so that if you only care about the REST API you don't have to figure out how to build an index first, since without an index the webapp won't run.

I think a solution for this for our purposes is for us to just build/publish a container for our usage with a pre-built index, but for the public repo let the user mount an index.

I'll remove the index files/implement that later today and update the PR.

**Comment by BeckySharp** [comment]
Marco also mentioned that we could add an endpoint to the webapp that
creates an index, so the user doesn't have to worry about that.  I can add
that, would it affect plans?

**Comment by brandomr** [comment]
I think that would definitely be preferable and won't conflict. Pretty much all I'll need to do is add instructions on how to mount your index volume and what to specify exactly in the config.

**Comment by BeckySharp** [comment]
yeah -- we can specify a location for the index, which will be mounted, and
I can add something to make the index there... i'll work on it this week,
thanks!

**Comment by brandomr** [comment]
Ok so I cleared out `docker/index` and added instructions to the README on where to put the index (default would be at `docker/index`). The user can really mount any index they wish from their localhost to any path on the container so long as it is correctly specified in `src/main/resources/application.conf`. 

I think the simplest thing for the build index endpoint would be to build an empty index in `docker/index`, which inside the Docker container is `/root/webapp/docker/index`.

**Comment by BeckySharp** [comment]
why an empty index?

**Comment by brandomr** [comment]
Ah, so I was thinking just about `/process_text`, but actually for the webapp you're right you would _not_ want to make an empty index, but a _real_ index!

Also, I realized that the `docker/index` directory is kind of arbitrary so if you'd rather remove that empty placeholder directory we could do that and the user would specify whichever mount they want. No preference on this on our end since it's ultimately equivalent.

**Comment by BeckySharp** [comment]
You know, I may also be able to make the part that needs an index to be
`lazy` so that it only loads if you are using the webapp itself, which
*should* remove your need for any index, real or otherwise if you're just
using `process_text`

**Comment by brandomr** [comment]
That would be great if easy enough to do.

**Comment by BeckySharp** [comment]
ok @brandomr  I added the no-index thing and I also modified the annotation to only include the necessary stuff and no extras.  This will reduce the time to process a little, but please see my comments in #6

**Comment by BeckySharp** [comment]
I think i'll merge (waiting a little to make sure you have a chance to voice concerns) and then i'll modify the readme to explain that you don't need an index for `process_text` (unless you want to do the honors, if you did go for it! any help is appreciated!!)

**Comment by brandomr** [comment]
Awesome, I updated the README with a note on that and removed `docker/index` since it can be created by the user or they can just mount whatever directory they want more or less wherever they want and specify it as a volume mount per the instructions.

**Pull request merged**
